name: build-pdf

on:
  push:
  workflow_dispatch:

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (incl. LFS for large images)
        uses: actions/checkout@v4
        with:
          lfs: true

      # Write build meta that main.tex \inputs (BuildRun/SHA/Date)
      - name: Write build metadata
        shell: bash
        run: |
          echo "\def\BuildRun{${{ github.run_number }}}"        >  buildmeta.tex
          echo "\def\BuildSHA{${GITHUB_SHA::7}}"               >> buildmeta.tex
          echo "\def\BuildDate{$(date -u +%Y-%m-%dT%H:%M:%SZ)}" >> buildmeta.tex
          echo "Wrote buildmeta.tex:"
          cat buildmeta.tex

      - name: Compile LaTeX (LuaLaTeX + biber)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          args: -halt-on-error -file-line-error
          extra_system_packages: biber

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf-${{ github.run_number }}
          path: main.pdf
